# Generated by Django 2.2.1 on 2019-06-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='temporary description', max_length=255),
            preserve_default=False,
        ),
    ]
